version: '3.7'

services:
  zetteltasken:
    build: ./docker/zetteltasken
    volumes:
      - ./projects/zetteltasken:/app
      - ./src:/src
    networks:
      - backend

  nginx:
    image: nginx:1.17.4-alpine
    volumes:
      - ./docker/sites-enabled:/etc/nginx/conf.d
      - ./projects/zetteltasken/frontend:/var/www/zetteltasken
    ports:
      - "80:80"
    networks:
      - backend

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
